database:
  user: "![CQg2p3O/isihdzkwJe5kVP2eTOY1W5fyyikqX5RNMLw=]"
  password: "![90jN/H+YHBZ9onqO4Z/SFjnenunAyBmar/LIFuulBCo=]"
  
email:
  password: "![Z7v2jwWvoWtR0dCUKUW+58VHonj4T3MDiWXrV8jGRUo=]"